version: "3.7"
services:

  useragent-parser-gateway:
    build: ./gateway
    image: gateway
    depends_on:
      - useragent-parser-rabbit
    networks:
      - messaging
    ports:
     - "5000:5000"
    volumes:
     - ./gateway/src:/usr/src/app/
    environment:
     - FLASK_ENV=development
     - SCALE=1
     - RETRY_DELAY=5
     - CONNECTION_ATTEMPTS=10

  useragent-parser-rabbit:
    image: rabbitmq:alpine
    networks:
      - messaging

  useragent-parser-worker:
    build: ./worker
    image: worker
    depends_on:
      - useragent-parser-rabbit
      - useragent-parser-gateway
    networks:
      - messaging
    volumes:
      - ./worker/src:/usr/src/app/
    environment:
     - SCALE=1
     - RETRY_DELAY=5
     - CONNECTION_ATTEMPTS=10

networks:
  messaging:
