FROM python:3-alpine
MAINTAINER Lucas Thisen <l.thiesen95@gmail.com> 

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /usr/src/app

CMD [ "python", "service.py" ]